version: '3.8'
services:

    #laravel
    php:
        build:
            context: ./src
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        ports:
            - 8000:8000
        depends_on:
            database:
                condition: service_healthy

    #database server
    database:
        image: mariadb:10.6.16
        ports:
            - 3307:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_DATABASE=${DB_DATABASE}
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot"]
            timeout: 20s
            retries: 10

    #frontend
    frontend:
        build: ./frontend
        ports:
            - 8081:8080
        depends_on:
            - php
volumes:
  db-data: ~
